ramda/ramda.github.io

0.10/index.html
0.9/index.html
index.html

Use Internet Archive mirror of Why Curry Helps.

---

docs/index.html
index.html
lib/doc/redir.tpl.js

this is a fix to help @raine use the unversioned docs url

pass url hash through on the redirect

---

repl/assets/js/repl.js
repl/index.html

repl: apply R.toString to output value

---

lib/doc/jsdoc-template/docs.html.handlebars

fixes this: http://ramdajs.com/docs/#transduce

docs: render multiple see also items separately

---

lib/doc/jsdoc-template/publish.js

see https://github.com/ramda/ramda/pull/1256#issuecomment-119698147

handle multi-line and comma-separated @see annotations

---

repl/assets/js/examples.js

REPL examples in ES6

---

repl/assets/css/repl.css

Same as https://github.com/ramda/ramda.github.io/pull/38

Better looking REPL

---

0.18.0/docs/index.html
docs/index.html

Closes #37
This pull request was enabled by ramda/ramda#1458. I applied the changes manually to prevent unwanted changes from sneaking in.

fix "see also" links

---

main.js
repl/index.html

updated the code for "Try in Repl" ... if you rebuild the docs with the `VERSION=0.19.0 make`  or whatever you guys use this should show a little "Try in Repl" button on the code snippets in the docs
i gave a shot in a separate branch and seems to work :smile:

try in repl update

---

README.md
package.json

Add http-server as a dev dependency and a npm script to start a local server.

Add http-server with npm script

---

repl/index.html

Apply URL change from 204eafb3

Fix REPL link on REPL page in navbar

---

jsdoc/publish.js
repl/index.html.handlebars
repl/lib/js/bundle.js
repl/lib/js/repl.js
repl/lib/js/reset.js
repl/npm-shrinkwrap.json
repl/package.json

This PR addresses several issues.

several fixes

---

0.19.1/docs/index.html

renamed `append` function to `appender`, works in REPL

append is already taken and will not work in REPL

---

custom.css
docs/index.html.handlebars

Fixes #80 Visual bug -- overflow <li> bounding box when name is too long

---

repl/index.html
repl/index.html.handlebars
repl/lib/js/bundle.js
repl/lib/js/main.js
repl/package.json

Notes
- Changes build script in `package.json` to add `./lib/js/main.js` into `./lib/js/bundle.js`
- Changes `./lib/js/main.js` variable declarations from `const` to `global.variable_name`
- Removes `<script>` tag for `./lib/js/main.js` inside `index.html` and `index.html.handlebars` since it is now integrated in the bundle

Resolves ramda/#1789

---

package.json

Alternative to #77, as discussed in comments.

Add ramda 0.21.0 dev dependency

---

0.20.1/index.html
0.21.0/index.html

fix CDN links

---

package.json

Prompted by discussion in #91.

Set ramda dependency to 0.22.1

---

make_releases_html.js
package.json
releases.html
releases.html.handlebars

Add releases script and page

---

docs/index.html.handlebars

Start of work on #74.
I'd like confirmation on how people want the types displayed.

Show each param type name

---

repl/lib/js/bundle.js

Related to #110 
I hadn't updated the `repl/lib/js/bundle.js` file! Very sorry!
I presume there are no deploy scripts that update compiled files and that is why they are checked in?

Include prettification in bundled js ... up to date

---

less/header.less

Steps taken: 
- Run SVG through [svgomg](https://jakearchibald.github.io/svgomg/)
- Remove `charset=utf8` from data URI
- Url encode SVG with [`encodeURIComponent`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent)

Optimize hamburger SVG data URI: fixes ramda/ramda.github.io#120

---

index.html

Replace redirect on index.html with README content

---

package.json

Add gitbook npm script

---

docs/index.html
docs/index.html.handlebars
index.html
index.html.handlebars

This still only updates the home and docs pages.
I need to confirm the appropriate process for updating the repl page.

Add Gitter to navbar and pull external links right

---

repl/index.html

just to get the repl up on its feet again. not a permanent solution

stop loading external script for now

---

index.pug
layout.pug
make_index_html.js
make_releases_html.js
package.json
releases.pug

Pug templates seem to have better support for inheritance than Handlebars.

Use Pug templates for index and releases pages

---

repl/index.html
repl/index.pug

Reverts ramda/ramda.github.io#190

Revert "Support versioning of ramda-repl js file"

---

repl/index.html
repl/index.html.handlebars

This changes the source for the external scripts from `wzrd.in` to `bundle.run`.

REPL: replace wizrd.in with bundle.run

---

repl/index.html
repl/index.html.handlebars

Should solve the problem in REPL.
Followed advice from @apollux discused [here](https://github.com/ramda/ramda/issues/3036#issuecomment-642415802)

Change from 'bundle.run' to 'unpkg.com' for S and ramda-fantasy

---

repl/index.html
repl/index.html.handlebars

This one should do. The problem is the sources were not for distribution. My bad.

Change sanctuary source to one bundled with deps

---

0.24.1/docs/main.js
0.25.0/docs/main.js
0.26.0/docs/main.js
0.26.1/docs/main.js
0.27.0/docs/main.js
docs/main.js

Use nodeVersion 14.x.x until Ramda updates the src pattern.
