ramda/ramda.github.io

docs/dist/ramda.js

In the `commuteMap` comment, `plus10map` is defined at the top, but then an identical 'inline' version is used immediately afterwards (`plus10map` is then used again in the next  two comments)

Make `commuteMap` example use `plus10map` consistently

---

lib/doc/jsdoc-template/docs.html.handlebars

This change adds a `View source on GitHub` link for each function.
If the change is welcome, do you want the updated generated docs html included as part of this PR as well?
Screenshot:

Adds link to github source for each function card

---

repl/assets/js/repl.js

It's surprising that [`{x: 1, y: 2}`][1] is a syntax error. Node's REPL does something [similar][2].
[1]: http://ramdajs.com/repl/?v=0.15.1#%7Bx%3A%201%2C%20y%3A%202%7D
[2]: https://github.com/joyent/node/blob/v0.12.6/lib/repl.js#L265-L276

repl: treat {x: 1, y: 2} as object literal rather than block statement

---

lib/doc/jsdoc-template/docs.html.handlebars
lib/doc/jsdoc-template/index.html.handlebars
lib/doc/less/header.less
lib/doc/less/layout.less
lib/doc/less/ramda.less
lib/doc/main.js

This PR contains my proposal for issue https://github.com/ramda/ramda.github.io/issues/24
This was my proof of concept, with the inner workings for the css-only hamburger behaviour:
http://codepen.io/branneman/pen/BNvNQB/left/?editors=110
This was of course only a quick fix for the sidebar, my final solution has an optimised header & menu as well.
And I made a short demo video of how it works and feels on a small screen:
https://www.youtube.com/watch?v=A60DCGq2yCo
@buzzdecafe: Unfortunately I ended up with a hamburger icon, because of the small amount of space available. I would've preferred something different as well, but I didn't get it to look nice. The good news is that it's fairly easy to change in `header.less`, if you can think up something better in the future.
As an aside, I ran …

First proposal for #24

---

0.10/docs/index.html
0.11/docs/index.html
0.12/docs/index.html
0.13/docs/index.html
0.14/docs/index.html
0.15/docs/index.html
0.16/docs/index.html
0.17/docs/index.html
0.9/docs/index.html
docs/index.html

Related to https://github.com/ramda/ramda/pull/1358
Also, it seems that there were two more occurrences of this errata in previous versions, but they were fixed in the src, so it just remains this one in the last version.

Fix minor description errata

---

Makefile
docs/dist/ramda.js
docs/index.html
docs/main.js

https://github.com/ramda/ramda.github.io/pull/34#issuecomment-147574783:
> We've been pointing <http://ramdajs.com/docs/> at the current build's API docs. I thought that had been automated by the build, but it didn't happen here.
I had thought that this target would match __docs/index.html__:
```make
%: $(VERSION)/%
cp '$<' '$@'
```
Apparently [`%`][1] does not perform matches across path components, so the target above matches __style.css__ but not __docs/index.html__.
[1]: https://www.gnu.org/software/make/manual/html_node/Static-Usage.html#Static-Usage

update "docs" directory

---

jsdoc/publish.js
jsdoc/templates/docs/index.html.handlebars
less/ramda.less
main.js

Dependent on #34, which I will merge before merging this pull request.
@CrossEye, please run `VERSION=0.18.0 make` to see whether you are happy with the following:
- the styling of type signatures;
- the handling of functions with multiple type signatures (see `R.take`, for example);
- the styling of type definitions (see `R.view`, for example);
- the links for toggling the visibility of parameter details; and
- the rendering of `@since` annotations.
I'll admit that the design looks a bit like a dog's breakfast with these additions, but this shouldn't prevent us from making useful content available to users. Presenting this content in a sensible manner will require time and thought from a designer such as @ricburton.

include @since, @typedefn, and additional @sig annotations

---

repl/lib/js/main.js

Functions that exist in both ramda and window are stored in a preservation object: _window

Expose ramda functions as default on window

---

repl/index.html

new repl lost the ability to specify the version of ramda to include in the repl. this repairs that oversight

respect requested version in querystring

---

repl/index.html
repl/index.html.handlebars
repl/lib/css/repl.css
repl/lib/css/terminal.css

This PR focuses on providing larger code viewing area for the REPL by removing or compacting the size of some page elements. It also has an improved viewing experience for small window sizes.
Small screen comparison between current and this PR:
Notes
- I get 403 from google for the "Make Short URL" button. I would guess the uri key just doesn't work for my origin.
- Still confused about the build process. I  tried a test run using `VERSION=0.21.0 make` from the parent folder to see if an edit in `repl/index.html.handlebars` would build into a new `repl/index.html`, but that didn't appear to work. (So I hand copied between html and handlebars file :hammer: )

Larger code viewing area

---

manual/01-intro/Immutability.md

I've been working through the manual trying the code snippets out in the node repl; this PR fixes the last two snippets on the Immutability page which failed.
* Replace comma with semicolon in "reduce without mutation" example
* Map `R.props` over filtered states in piped example and make code layout suitable for pasting in node repl

Small fixes to last two immutability code snippets

---

custom.css
docs/index.html.handlebars
jsdoc/publish.js
less/custom.less
less/ramda.less

original issue: https://github.com/ramda/ramda/issues/1776
the complementary PR for ramda/ramda: https://github.com/ramda/ramda/pull/1852

adds-symbols - initial commit

---

copy_ramda_js.js
get_ramda_file.js

Adds a script (`copy_ramda_js.js`) that will copy the ramda.js file from the `node_modules` folder and into the repository.
This is the other part of #77, following on from #86.

Add copy ramda.js script

---

make_index_html.js

This requires `get_ramda_file.js` from #91 and the index template moved in #90.
Use `node make_index_html.js` to create `index.html` using `index.html.handlebars` and `README.md` (from the `ramda` repo).

Add make index.html script

---

copy_to_version_folder.js
package.json

Creates a folder named as the Ramda version number and then copies documentation into it.
Run with `node copy_to_version_folder.js`.

Add copy to version folder script

---

Makefile

Now there is no index page, because when user visits `/` he is auto
redirected to `/<version>/docs` page.
Prevents #105 from happening again

Don't copy docs main.js to index directory

---

repl/index.html
repl/index.html.handlebars
repl/lib/css/repl.css

Relates to issue #96 
This PR adds some extra CSS classes and rules with the objective of making the elements containing the `CodeMirror` have a full height, thereby increasing the click target for giving focus to the `CodeMirror`.
Tested on modern versions of Chrome, Firefox and Microsoft Edge.

Fix #96 Ensure codemirror is full height

---

repl/index.html
repl/index.html.handlebars
repl/lib/js/pretty.js
repl/lib/js/repl.js
repl/npm-shrinkwrap.json
repl/package.json

This adds a `Pretty Output` button next to the existing `Clear Output` button. A user can press it to attain a formatted view of their output text.

Add 'pretty output' button

---

Makefile
browserslist
package.json

Some vendor prefixes are missing (e.g: `-webkit-transform`). This is causing issues especially on mobile (iOS < 9, Android < 4.3): https://github.com/ramda/ramda.github.io/issues/41.
[Autoprefixer](https://github.com/less/less-plugin-autoprefix) automatically adds these prefixes to css after conversion from less. The targeted browsers are listed in the `browserslist` config file.
The browser versions are based on what's specified for the unit tests:
- https://github.com/ramda/ramda/blob/master/lib/sauce/android.js
- https://github.com/ramda/ramda/blob/master/lib/sauce/apple.js
- https://github.com/ramda/ramda/blob/master/lib/sauce/ios.js
To mitigate the increased file size after autoprefixing (before: 147kb, after: 152kb) I've added minification to the build process as well. This reduces …

Missing vendor prefixes 

---

docs/main.js

Fixes #144
This contains a hack to deal with the REPL discarding the first character.
The semicolon should ensure the code is still valid if the first character is included later.

Fix try in REPL link in docs

---

ramdocs/docs/index.html
ramdocs/index.html

Just thought I'd see if the `ramdocs` redirects were still needed.

Remove ramdocs redirects

---

repl/index.html

The URLs seems to be working and the globals S and ramdaFantasy are exposed in the REPL

Enable loading of external scripts

---

index.pug
layout.pug
less/layout.less
less/ramda.less
less/repl.less
make_index_html.js
make_repl_index_html.js
repl/css/page.css
repl/index.js
repl/index.pug

This does not include the compiled HTML or CSS files (I'll add those if this is approved or in a later PR).
It includes a Pug template for the REPL that is based off the common layout template.
So it fixes the version number in the header.

Update Pug templates

---

repl/index.html
repl/index.pug

We started to use `rawgit` since https://github.com/ramda/ramda.github.io/pull/136. From the comment in https://github.com/ramda/repl/pull/50#issuecomment-331756404, [rawgit faq](https://github.com/rgrove/rawgit/blob/master/FAQ.md#how-long-does-the-cdn-cache-files-how-can-i-make-it-refresh-my-file) does not recommend using `master` as the tag as they do not clear cache. 
This PR attempts to use tag from `ramda-repl` instead of always using `master` to overcome this issue.
I also added a util script to generate the repl/index.html from handlerbars. Sorry that I could not figure out how to use the new pug based template introduced in https://github.com/ramda/ramda.github.io/pull/175. It also looks like the current repl/index.html has been manually modified in the past few commits. Feel free …

Support versioning of ramda-repl js file

---

docs/index.html.handlebars

We broke the links to the source code in the docs when we moved from `src` to `source`.

Fixing source-code links (Closes #197)

---

.jsdoc.config.json
0.25.0/docs/index.html
docs/index.html
package.json

Fixed docs

---

repl/index.html
repl/index.pug

This reverts PR #194, which is a revert of #190

Revert "Revert "Support versioning of ramda-repl js file""

---

docs/index.html.handlebars

Safari tries to autofill the input without the `autocomplete="false"`

fix: Disable autocompletion for the search input in Safari

---

0.25.0/docs/index.html
docs/index.html

Update example variable name from `values` to `vals`. When running this code on the Ramda REPL name `values` conflicts with `R.values` that is globally scoped, therefore the code does not run.

mapObjIndexed - Update code example

---

0.25.0/docs/main.js
0.26.0/docs/main.js
0.26.1/docs/main.js
docs/main.js

This brings `Either` and `Maybe` into scope for RunKit embeds. I back-ported it to 0.25.0 and 0.26.0 (along with the current 0.26.1) to support all the versions that have used RunKit embeds.

Add Either and Maybe to RunKit embeds

---

index.html

Thanks again for linking to my Thinking in Ramda blog series from this page! I get a lot of positive feedback on the series, and it looks like most people find it via this link.
I've just updated my site to use https, so this updates the link series to be https instead of http.
Apologies for the spurious extra newline at the end of the diff.  I submitted this directly using GitHub's UI and they must have added it.

Use https for Randy Coulman's Thinking in Ramda

---

repl/index.html
repl/index.pug

This is to bump up the version of repl to 1.2.0 to bring in the changes for using tinyurl as the url shortener to replace the now defunct google one.
See https://github.com/ramda/repl/pull/69

bump up repl version to 1.2.0 to use tinyurl for url shortening

---

repl/index.html
repl/index.html.handlebars
repl/index.js

This probably happened at some point when changing the cdn. Also changed the url to point to `@latest` like sanctuary, although this is not probably not very relevant for `ramda-fantasy`.

fixes repl loading ramda-fantasy types

---

publish.js

@kedashoe Ramda Doc use `R.propEq` to filter every functions' "category" tag, and ramda swap `R.propEq` parameters order in v0.29.0, this is the reason Ramda Doc lost "category" tag.
We need to merge this pr, and republish ramda doc.

bugfix: fix Filter no category

---

0.25.0/docs/index.html
0.25.0/docs/index.html.handlebars
0.26.0/docs/index.html
0.26.0/docs/index.html.handlebars
0.26.1/docs/index.html
0.26.1/docs/index.html.handlebars
0.27.0/docs/index.html
0.27.0/docs/index.html.handlebars
0.27.1/docs/index.html
0.27.1/docs/index.html.handlebars
0.27.2/docs/index.html
0.27.2/docs/index.html.handlebars
0.28.0/docs/index.html
0.28.0/docs/index.html.handlebars
0.29.0/docs/index.html
0.29.0/docs/index.html.handlebars
0.29.1/docs/index.html
0.29.1/docs/index.html.handlebars
0.30.0/docs/index.html
0.30.0/docs/index.html.handlebars
0.30.1/docs/index.html
0.30.1/docs/index.html.handlebars
docs/index.html
docs/index.html.handlebars

The titles of the API Docs were  `Ramda Documentationa` instead of  `Ramda Documentation` 
fixes #287

fix(documentation): Corrected typo in API Docs page title
